name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build backend with Maven
        run: mvn clean package -DskipTests
        working-directory: ./lab_grupa_b

      - name: Build frontend with Yarn
        run: |
          yarn install
          CI=false yarn build
        working-directory: ./frontend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_proektna_frontend:latest

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./lab_grupa_b
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_proektna:latest

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f ./docker-compose.yml up -d
